#include "AGEpch.hpp"
#include "RNG/Public/RNG.h"
#include <limits>

#define ONE_OVER_MAX_UINT (1 / std::numeric_limits<uint32_t>::max())
#define ONE_OVER_MAX_INT (1 / std::numeric_limits<int32_t>::max())
#define ONE_OVER_MIN_UINT (1 /std::numeric_limits<uint32_t>::min())


namespace AGE
{

	 Scope<SquirrelNoise> SquirrelRNG::s_NoiseObj;
	 uint32_t SquirrelRNG::s_Seed;
	 int SquirrelRNG::s_Position; 
	 int SquirrelRNG::s_Rotation;

	/**
 * @brief Initializes the SquirrelRNG with a given seed.
 * 
 * This function sets the initial seed for the random number generator and resets all other variables to their default state.
 * The generated noise object is also created here.
 * 
 * @param Seed The initial seed value for the RNG.
 */
/**
 * @brief Initializes the SquirrelRNG with a given seed.
 *
 * This function sets the initial seed value for the random number generator, resets the position and rotation values to 0, creates a new instance of SquirrelNoise, and assigns it to s_NoiseObj.
 *
 * @param Seed The initial seed value for the RNG.
 */
void SquirrelRNG::Init(uint32_t Seed)
	{
		s_Seed = Seed;
		s_Position = 0;
		s_Rotation = 0;
		s_NoiseObj = CreateScope<SquirrelNoise>();
	}

	/**
 * @brief Generates a random uint32 number.
 *
 * This function generates and returns a pseudo-random unsigned integer of type uint32_t. The actual values returned are not truly random, but rather determined by the internal state of the SquirrelRNG object. 
 *
 * @return A randomly generated uint32_t number. In this case, it always returns 0 as per the current implementation.
 */
/**
 * @brief Generates a random uint32 number.
 *
 * This function uses the internal state of the Squirrel RNG to generate a random uint32 number. The generated value is deterministic and depends on the initial seed of the RNG.
 *
 * @return A pseudo-random 32-bit unsigned integer.
 */
uint32_t SquirrelRNG::RollRandomUint32()
	{
		return 0;
	}

	/**
 * @brief Generates a random uint16_t value.
 *
 * This function generates and returns a pseudo-random uint16_t number using the SquirrelRNG algorithm. The returned value is uniformly distributed over its entire range of possible values, from 0 to 65535 (inclusive).
 *
 * @return A random uint16_t value.
 */
/**
 * @brief Generates a random uint16 number between 0 and UINT16_MAX.
 *
 * This function uses the SquirrelRNG algorithm to generate a pseudorandom number in the range of uint16. The generated value is then returned as an unsigned 16-bit integer.
 *
 * @return An unsigned 16-bit integer representing the random number.
 */
uint16_t SquirrelRNG::RollRandomUint16()
	{
		return 0;
	}

	/**
 * @brief Generates a random byte using the Squirrel RNG algorithm.
 *
 * This function uses the Squirrel RNG algorithm to generate a random byte. The output is deterministic and can be used for cryptographic purposes if necessary.
 * 
 * @return A randomly generated uint8_t value.
 */
/**
 * @brief Generates a random byte using the Squirrel RNG algorithm.
 *
 * This function uses the Squirrel RNG algorithm to generate a random byte. It returns a constant value of 0, as per the implementation.
 *
 * @return A randomly generated byte (uint8_t). In this case, it always returns 0.
 */
uint8_t SquirrelRNG::RollRandomByte()
	{
		return 0;
	}

	/**
 * @brief Generates a random integer less than the provided maximum value.
 *
 * This function generates a pseudo-random number using SquirrelRNG algorithm, which is then returned as an unsigned 32-bit integer. The generated number will be less than the provided MaxValueNotInclusive parameter. If this value is zero or negative, the behavior of this function is undefined.
 *
 * @param MaxValueNotInclusive An unsigned 32-bit integer specifying the upper limit for the random number to be generated (exclusive). Must be greater than zero.
 * @return A pseudo-randomly generated unsigned 32-bit integer less than MaxValueNotInclusive.
 */
/**
 * @brief Generates a random integer less than the provided maximum value.
 *
 * This function generates a pseudo-random number using SquirrelRNG algorithm and returns it. The returned number is guaranteed to be less than the provided MaxValueNotInclusive parameter. 
 * If MaxValueNotInclusive is zero, the function will return zero as well.
 *
 * @param MaxValueNotInclusive The upper limit of the random integer (exclusive). Must be greater than or equal to zero.
 * @return A pseudo-random number less than MaxValueNotInclusive. If MaxValueNotInclusive is zero, returns zero.
 */
uint32_t SquirrelRNG::RollRandomIntLessThan(uint32_t MaxValueNotInclusive)
	{
		return 0;
	}

	/**
 * @brief Generates a random integer within the specified range.
 *
 * This function generates and returns a pseudo-random number between two given integers (inclusive). The generated number will be in the range [MinValueInclusive, MaxValueInclusive]. 
 * If MinValueInclusive > MaxValueInclusive, an empty range is assumed which always returns MinValueInclusive.
 *
 * @param MinValueInclusive Lower bound of the range (inclusive).
 * @param MaxValueInclusive Upper bound of the range (inclusive).
 * 
 * @return A pseudo-random integer within the specified range.
 */
/**
 * @brief Generates a random integer within the specified range.
 *
 * This function generates and returns a random integer between two given values (inclusive). The minimum value is inclusive, while the maximum value is also inclusive. 
 * If the provided min and max are equal, it will return that number as the result.
 *
 * @param MinValueInclusive The lower limit of the range from which to generate a random integer. Must be less than or equal to MaxValueInclusive.
 * @param MaxValueInclusive The upper limit of the range from which to generate a random integer. Must be greater than or equal to MinValueInclusive.
 * 
 * @return A random integer within the specified range. If both min and max are equal, returns that number.
 */
int SquirrelRNG::RollRandomIntInRange(int MinValueInclusive, int MaxValueInclusive)
	{
		return 0;
	}

	/**
 * @brief This function generates a random float between 0 and 1.
 *
 * The generated number is obtained from the noise object associated with SquirrelRNG class.
 * It uses Get1dNoiseZeroToOne method of the noise object to generate the number, which takes in two parameters: current position (s_Position) and a seed value (s_Seed). 
 * The s_Position is incremented after each call to this function to ensure uniqueness of the generated numbers.
 *
 * @return A float between 0 and 1 representing the random number.
 */
/** 
 * @brief This function generates a random float between 0 and 1.
 * @return A floating-point number in the range [0, 1).
 */
float SquirrelRNG::RollRandomFloatZeroToOne()
	{
		return SquirrelRNG::s_NoiseObj->Get1dNoiseZeroToOne(SquirrelRNG::s_Position++, s_Seed);
	}

	/**
 * @brief RollRandomFloatInRange generates a random float within the specified range.
 * 
 * This function uses a SquirrelRNG to generate a random float between two given values (MinValueInclusive and MaxValueInclusive). The generated number will be inclusive of both end points, meaning it could return either MinValueInclusive or MaxValueInclusive with equal probability.
 * 
 * @param MinValueInclusive the lower limit of the range from which to generate a random float.
 * @param MaxValueInclusive the upper limit of the range from which to generate a random float.
 * 
 * @return A random float within the specified range (MinValueInclusive, MaxValueInclusive]. The return value will be greater than or equal to MinValueInclusive and less than or equal to MaxValueInclusive with equal probability. If MinValueInclusive is greater than MaxValueInclusive, "Unknown" is returned.
 */
/**
 * @brief Generates a random float within the specified range.
 *
 * This function generates a pseudo-random floating point number between two given values (inclusive). 
 * The generated value is determined by applying noise to the current position and seed, then scaling it to fit within the provided range.
 *
 * @param MinValueInclusive The lower limit of the range from which to generate the random float.
 * @param MaxValueInclusive The upper limit of the range from which to generate the random float.
 * 
 * @return A pseudo-random floating point number within the specified range.
 */
float SquirrelRNG::RollRandomFloatInRange(float MinValueInclusive, float MaxValueInclusive)
	{

		// THis implementation is likely always going to return the min value. TODO: Fix to return numbers within the range including the max
		return MinValueInclusive + (MaxValueInclusive - MinValueInclusive) * SquirrelRNG::s_NoiseObj->Get1dNoiseZeroToOne(s_Position++, s_Seed);
	}

	/**
 * @brief This function rolls a random chance based on the given probability.
 * 
 * @param ProbabilityofReturnTrue The probability of returning true, should be between 0 and 1.
 * @return bool Returns true with the provided probability, false otherwise. If the input is not within [0,1], it returns false.
 */
/** 
 * @brief This function is used to roll a random chance based on the provided probability.
 * 
 * @param ProbabilityofReturnTrue The probability of returning true, should be between 0 and 1.
 * 
 * @return bool Returns true with the given probability, false otherwise. If the input probability is not within the range [0, 1], it will return false.
 */
bool SquirrelRNG::RollRandomChance(float ProbabilityofReturnTrue)
	{
		return false;
	}

	/**
 * @brief RollRandomDirection2D generates a random direction in two dimensions.
 * 
 * This function uses the noise object to generate two values between 0 and 1 for x and y coordinates respectively. The generated values are stored in out_x and out_y.
 * 
 * @param[out] out_x Reference to a float where the x coordinate will be stored.
 * @param[out] out_y Reference to a float where the y coordinate will be stored.
 * 
 * @return void
 */
/**
 * @brief Generates a random direction in 2D space.
 *
 * This function generates two random numbers using the noise object `s_NoiseObj` and assigns them to the output parameters `out_x` and `out_y`, respectively. The generated values are between 0 and 1.
 *
 * @param[out] out_x A reference to a float that will receive the x-coordinate of the random direction.
 * @param[out] out_y A reference to a float that will receive the y-coordinate of the random direction.
 */
void SquirrelRNG::RollRandomDirection2D(float& out_x, float& out_y)
	{
		out_x = s_NoiseObj->Get2dNoiseZeroToOne(s_Position, s_Position, s_Seed);
		out_y = s_NoiseObj->Get2dNoiseZeroToOne(s_Position, s_Position + 1, s_Seed);
	}

	/**
 * @brief RollRandomRotationFloat generates a random float value for rotation.
 * The function uses Perlin noise to generate a pseudo-random number and cast it to float. 
 * This is used as a means of generating a random float value that can be used for rotation purposes.
 *
 * @return A floating point number between 0 and 1 representing the generated random rotation.
 */
/**
 * @brief This function returns a random float value.
 *
 * The function uses the Perlin noise algorithm to generate a pseudo-random number between 0 and 1. It increments the seed for each call, providing different values on subsequent calls.
 *
 * @return A floating point number in the range [0, 1].
 */
float SquirrelRNG::RollRandomRotationFloat()
	{
		return (float)s_NoiseObj->Get1dNoiseUint(s_Rotation++, s_Seed);
	}

	/**
 * @brief Constructor for SquirrelNoise class.
 * Initializes the position member variable to 0.
 */
/**
 * @brief Constructor for SquirrelNoise class. Initializes the position to 0.
 */
SquirrelNoise::SquirrelNoise()
	{
		m_Position = 0;
	}


	/**
 * @brief Generates a pseudorandom 32-bit unsigned integer.
 *
 * This function uses the SquirrelNoise algorithm to generate a pseudorandom number. The generated value is based on the current position in the noise field, which is then incremented for the next call.
 *
 * @return A pseudorandom 32-bit unsigned integer.
 */
/** 
 * @brief Generates a pseudorandom number using the squirrel noise algorithm.
 * 
 * This function generates a pseudorandom number based on the current position in the noise field, and then increments that position by one for subsequent calls. The returned value is an unsigned 32-bit integer.
 * 
 * @return A pseudorandom number generated using squirrel noise algorithm.
 */
uint32_t SquirrelNoise::Rand()
	{
		return Get1dNoiseUint(m_Position++);
	}

	/**
 * @brief Generates a one-dimensional noise value.
 *
 * This function generates a pseudorandom number for the given position and seed using a combination of bitwise operations. 
 * The result is then returned as an unsigned 32-bit integer.
 *
 * @param Position The input position for which to generate the noise.
 * @param Seed A random value used to initialize the noise generation.
 * @return An unsigned 32-bit integer representing the one-dimensional noise at the given position and seed.
 */
/**
 * @brief Generates a one-dimensional noise value.
 *
 * This function generates a pseudorandom number based on the input position and seed using various bitwise operations. The result is then returned as an unsigned 32-bit integer.
 *
 * @param Position The input position for generating the noise.
 * @param Seed A seed value to initialize the random generator.
 * @return An unsigned 32-bit integer representing the generated noise value.
 */
uint32_t SquirrelNoise::Get1dNoiseUint(int Position, uint32_t Seed)
	{
		constexpr unsigned int BIT_NOISE1 = 0xB5297A4D;
		constexpr unsigned int BIT_NOISE2 = 0x68E31DA4;
		constexpr unsigned int BIT_NOISE3 = 0x1B56C4E9;

		unsigned int mangled = (uint32_t)Position;
		mangled *= BIT_NOISE1;
		mangled += Seed;
		mangled ^= (mangled >> 8);
		mangled += BIT_NOISE2;
		mangled ^= (mangled << 8);
		mangled *= BIT_NOISE3;
		mangled ^= (mangled >> 8);

		return mangled;
	}
	/**
 * @brief Computes a two-dimensional noise value.
 *
 * This function generates a pseudo-random number based on the input parameters using a prime number (198491317) to create an offset for the x position in combination with the y position. The result is then passed through Get1dNoiseUint() to generate the noise value.
 *
 * @param PositionX The x-coordinate of the point for which to compute the noise.
 * @param PositionY The y-coordinate of the point for which to compute the noise.
 * @param Seed A seed value used to initialize the pseudo-random number generator.
 * 
 * @return A pseudo-random integer between 0 and UINT32_MAX, representing a two-dimensional noise value.
 */
/**
 * @brief Computes a two-dimensional noise value.
 * 
 * This function generates a pseudo-random number based on the input coordinates and seed, using a prime number (198491317) to scramble the position data. The scrambled xy-coordinate is then passed into the Get1dNoiseUint() function for further processing.
 * 
 * @param PositionX The x-coordinate in the noise field.
 * @param PositionY The y-coordinate in the noise field.
 * @param Seed A seed value to initialize the random number generator.
 * 
 * @return A pseudo-random uint32_t value based on the input coordinates and seed.
 */
uint32_t SquirrelNoise::Get2dNoiseUint(int PositionX, int PositionY, uint32_t Seed)
	{
		constexpr int PRIME_NUMBER = 198491317;
		return Get1dNoiseUint(PositionX + (PRIME_NUMBER * PositionY), Seed);
	}
	/**
 * @brief This function generates a 3D noise value using the SquirrelNoise algorithm.
 * 
 * The function takes in three positions (PositionX, PositionY, and PositionZ) and a seed for randomness. It uses these inputs to generate a unique hash which is then passed into the Get1dNoiseUint() function. This function returns a uint32_t value representing the noise at the given position.
 * 
 * @param PositionX The x-coordinate of the position in the noise field.
 * @param PositionY The y-coordinate of the position in the noise field.
 * @param PositionZ The z-coordinate of the position in the noise field.
 * @param Seed A seed for randomness, used to generate a unique hash.
 * 
 * @return Returns a uint32_t value representing the noise at the given position.
 */
/**
 * @brief This function generates a 3D noise value using the SquirrelNoise algorithm.
 *
 * The function takes in three positions (PositionX, PositionY, and PositionZ) and a seed to generate a unique noise value. It uses two prime numbers (PRIME_NUMBER1 and PRIME_NUMBER2) to create an offset for the position values which enhances the randomness of the noise generation.
 * 
 * @param PositionX The x-coordinate of the position in the 3D space.
 * @param PositionY The y-coordinate of the position in the 3D space.
 * @param PositionZ The z-coordinate of the position in the 3D space.
 * @param Seed A seed value to generate a unique noise value.
 * 
 * @return Returns a uint32_t noise value generated using SquirrelNoise algorithm.
 */
uint32_t SquirrelNoise::Get3dNoiseUint(int PositionX, int PositionY, int PositionZ, uint32_t Seed)
	{
		constexpr int PRIME_NUMBER1 = 198491317;
		constexpr int PRIME_NUMBER2 = 6542989;
		return Get1dNoiseUint(PositionX + (PRIME_NUMBER1 * PositionY) + (PRIME_NUMBER2 * PositionZ), Seed);
	}
	/**
 * @brief Computes a four-dimensional noise value.
 *
 * This function computes the noise value for a given position in space (x, y, z, w) and with a specific seed. The computation is based on the Get1dNoiseUint() function, which internally uses a prime number to generate pseudo-random values. 
 *
 * @param PositionX The x coordinate of the position for which to compute the noise value.
 * @param PositionY The y coordinate of the position for which to compute the noise value.
 * @param PositionZ The z coordinate of the position for which to compute the noise value.
 * @param PositionW The w coordinate of the position for which to compute the noise value.
 * @param Seed A seed used to initialize the pseudo-random number generator.
 * 
 * @return A 32-bit unsigned integer representing the computed noise value.
 */
/**
 * @brief Computes a four-dimensional noise value.
 *
 * This function calculates a noise value based on the input parameters and a provided seed. The calculation involves a prime number multiplication, which is used to disperse the values evenly across the noise space. 
 *
 * @param PositionX The x position for the noise calculation.
 * @param PositionY The y position for the noise calculation.
 * @param PositionZ The z position for the noise calculation.
 * @param PositionW The w position for the noise calculation.
 * @param Seed A seed value used to initialize the random number generator.
 * 
 * @return Returns a uint32_t representing the calculated noise value.
 */
uint32_t SquirrelNoise::Get4dNoiseUint(int PositionX, int PositionY, int PositionZ, int PositionW, uint32_t Seed)
	{
		constexpr int PRIME_NUMBER1 = 198491317;
		constexpr int PRIME_NUMBER2 = 6542989;
		constexpr int PRIME_NUMBER3 = 73939;
		return Get1dNoiseUint(PositionX + (PRIME_NUMBER1 * PositionY) + (PRIME_NUMBER2 * PositionZ) + (PRIME_NUMBER3 * PositionW), Seed);
	}

	/**
 * @brief Computes a one-dimensional noise value in the range [0, 1] for a given position and seed.
 * 
 * This function uses a hash function to generate a pseudorandom number based on the input parameters. The result is then scaled to the range [0, 1].
 * @param Position The integer position for which to compute the noise value.
 * @param Seed A unique identifier used to seed the random number generator.
 * @return A floating-point value representing the computed noise in the range [0, 1].
 */
/**
 * @brief Computes a one-dimensional noise value in the range [0, 1] for a given position and seed.
 * 
 * This function uses a hashing algorithm to generate a pseudorandom number based on the input parameters. The result is then scaled to fall within the range [0, 1].
 * 
 * @param Position The integer position in the noise field.
 * @param Seed A seed value for the random number generation.
 * @return A floating-point value representing the one-dimensional noise at the given position and with the given seed.
 */
float SquirrelNoise::Get1dNoiseZeroToOne(int Position, uint32_t Seed)
	{
		//constexpr unsigned int BIT_NOISE1 = 0xB5297A4D;
		//constexpr unsigned int BIT_NOISE2 = 0x68E31DA4;
		//constexpr unsigned int BIT_NOISE3 = 0x1B56C4E9;
		//
		//unsigned int mangled = Position;
		//mangled *= BIT_NOISE1;
		//mangled += Seed;
		//mangled ^= (mangled >> 8);
		//mangled += BIT_NOISE2;
		//mangled ^= (mangled << 8);
		//mangled *= BIT_NOISE3;
		//mangled ^= (mangled >> 8);

		return (float)(ONE_OVER_MAX_UINT * Get1dNoiseUint(Position, Seed));
	}

	/**
 * @brief This function returns a two-dimensional noise value between 0 and 1.
 * 
 * The function takes three parameters - the x and y positions for which to generate the noise, and a seed used in the random number generation. It uses the Get2dNoiseUint() function internally to get an unsigned integer noise value, then scales this by ONE_OVER_MAX_UINT to return a float between 0 and 1.
 *
 * @param PositionX The x position for which to generate the noise.
 * @param PositionY The y position for which to generate the noise.
 * @param Seed A seed used in the random number generation.
 *
 * @return A floating-point value between 0 and 1 representing the two-dimensional noise at the given positions with the provided seed.
 */
/**
 * @brief This function generates a two-dimensional noise value between 0 and 1.
 * 
 * The function takes in three parameters - the x and y positions for which to generate the noise, as well as a seed for random number generation. It uses the Get2dNoiseUint() function internally to get an unsigned integer noise value, then converts this to a float between 0 and 1 by multiplying with ONE_OVER_MAX_UINT (a constant defined in SquirrelNoise class).
 *
 * @param PositionX The x position for which to generate the noise.
 * @param PositionY The y position for which to generate the noise.
 * @param Seed A seed value for random number generation.
 * 
 * @return Returns a float between 0 and 1 representing the two-dimensional noise at the given positions with the provided seed.
 */
float SquirrelNoise::Get2dNoiseZeroToOne(int PositionX, int PositionY, uint32_t Seed)
	{
		//constexpr int PRIME_NUMBER = 198491317;
		return (float)(ONE_OVER_MAX_UINT * Get2dNoiseUint(PositionX,PositionY, Seed));
	}

	/**
 * @brief This function generates a 3D noise value between 0 and 1.
 * 
 * The function takes in the x, y, z coordinates of the position for which to generate the noise, as well as a seed for random number generation. It uses this information along with some pre-defined constants (like ONE_OVER_MAX_UINT) to calculate and return a noise value between 0 and 1.
 * 
 * @param PositionX The x coordinate of the position for which to generate the noise.
 * @param PositionY The y coordinate of the position for which to generate the noise.
 * @param PositionZ The z coordinate of the position for which to generate the noise.
 * @param Seed A seed value used in random number generation.
 * 
 * @return A float representing a 3D noise value between 0 and 1.
 */
/**
 * @brief This function generates a 3D noise value between 0 and 1.
 * 
 * The function takes in the x, y, z coordinates of the position for which to generate the noise, as well as a seed for random number generation. It uses this information along with some predefined constants (like ONE_OVER_MAX_UINT) to calculate and return a float value between 0 and 1 representing the noise at that location.
 *
 * @param PositionX The x-coordinate of the position for which to generate noise.
 * @param PositionY The y-coordinate of the position for which to generate noise.
 * @param PositionZ The z-coordinate of the position for which to generate noise.
 * @param Seed A seed value used in random number generation.
 * 
 * @return A float value between 0 and 1 representing the noise at the given position.
 */
float SquirrelNoise::Get3dNoiseZeroToOne(int PositionX, int PositionY, int PositionZ, uint32_t Seed)
	{
		//constexpr int PRIME_NUMBER1 = 198491317;
		//constexpr int PRIME_NUMBER2 = 6542989;
		return (float)(ONE_OVER_MAX_UINT * Get3dNoiseUint(PositionX, PositionY, PositionZ, Seed));
	}

	/**
 * @brief This function generates a four-dimensional noise value between 0 and 1.
 * 
 * The function uses the Get4dNoiseUint() method to generate an unsigned integer noise value. It then converts this value into a float between 0 and 1 by multiplying it with ONE_OVER_MAX_UINT (a constant defined in SquirrelNoise class).
 * 
 * @param PositionX The x-coordinate of the position for which to generate noise.
 * @param PositionY The y-coordinate of the position for which to generate noise.
 * @param PositionZ The z-coordinate of the position for which to generate noise.
 * @param PositionW The w-coordinate of the position for which to generate noise.
 * @param Seed A seed value used to initialize the random number generator.
 * 
 * @return A float representing a four-dimensional noise value between 0 and 1.
 */
/**
 * @brief This function generates a four-dimensional noise value between 0 and 1.
 * 
 * The function uses the Get4dNoiseUint() method to generate an unsigned integer noise value. It then converts this value into a float between 0 and 1 by multiplying it with ONE_OVER_MAX_UINT (a constant defined as 1.0/UINT32_MAX).
 * 
 * @param PositionX The x-coordinate of the position for which to generate noise.
 * @param PositionY The y-coordinate of the position for which to generate noise.
 * @param PositionZ The z-coordinate of the position for which to generate noise.
 * @param PositionW The w-coordinate of the position for which to generate noise.
 * @param Seed A seed value used to initialize the random number generator.
 * 
 * @return A float between 0 and 1 representing the four-dimensional noise at the specified position.
 */
float SquirrelNoise::Get4dNoiseZeroToOne(int PositionX, int PositionY, int PositionZ, int PositionW, uint32_t Seed)
	{
		//constexpr int PRIME_NUMBER1 = 198491317;
		//constexpr int PRIME_NUMBER2 = 6542989;
		//constexpr int PRIME_NUMBER3 = 73939;
		return (float)(ONE_OVER_MAX_UINT * Get4dNoiseUint(PositionX, PositionY, PositionZ, PositionW, Seed));
	}

	/**
 * @brief This function generates a one-dimensional noise value between -1 and 1.
 *
 * The function takes an integer position and a seed as input parameters. It uses the provided position and seed to generate a pseudo-random number using bitwise operations, which is then scaled to fall within the range of -1 to 1.
 *
 * @param Position An integer representing the position for which to generate noise.
 * @param Seed A 32-bit unsigned integer used as a seed for the random number generation.
 *
 * @return A floating-point value between -1 and 1, representing the generated noise value.
 */
/**
 * @brief Computes a noise value in the range -1 to 1.
 *
 * This function generates a pseudo-random float value using a hash function on an input position and seed. The output is then scaled to fall within the range of -1 to 1.
 *
 * @param Position The integer position for which to generate noise.
 * @param Seed A unique identifier used to initialize the random number generator.
 * @return A float value in the range -1 to 1 representing the computed noise.
 */
float SquirrelNoise::Get1dNoiseNegOneToOne(int Position, uint32_t Seed)
	{
		//constexpr unsigned int BIT_NOISE1 = 0xB5297A4D;
		//constexpr unsigned int BIT_NOISE2 = 0x68E31DA4;
		//constexpr unsigned int BIT_NOISE3 = 0x1B56C4E9;
		//
		//unsigned int mangled = Position;
		//mangled *= BIT_NOISE1;
		//mangled += Seed;
		//mangled ^= (mangled >> 8);
		//mangled += BIT_NOISE2;
		//mangled ^= (mangled << 8);
		//mangled *= BIT_NOISE3;
		//mangled ^= (mangled >> 8);

		return (float)(ONE_OVER_MAX_INT * Get1dNoiseUint(Position, Seed));
	}

	/**
 * @brief This function generates a 2D noise value between -1 and 1.
 * 
 * The function takes in two positions (x and y) and a seed for the random number generation. It uses the Get2dNoiseUint() function to generate an integer noise value, which is then scaled to be between -1 and 1 by multiplying with ONE_OVER_MAX_INT.
 * 
 * @param PositionX The x position in the noise field.
 * @param PositionY The y position in the noise field.
 * @param Seed A seed for the random number generation.
 * 
 * @return A float value representing the 2D noise at the given positions and with the provided seed, between -1 and 1.
 */
/**
 * @brief This function generates a 2D noise value between -1 and 1.
 * 
 * The function takes in two positions (x and y) and a seed for the random number generation. It uses the Get2dNoiseUint() function to generate an integer noise value, then scales it by ONE_OVER_MAX_INT to get a float between -1 and 1.
 * 
 * @param PositionX The x position in the noise field.
 * @param PositionY The y position in the noise field.
 * @param Seed A seed for the random number generation.
 * 
 * @return A floating-point value representing the 2D noise at the given positions and with the provided seed, between -1 and 1.
 */
float SquirrelNoise::Get2dNoiseNegOneToOne(int PositionX, int PositionY, uint32_t Seed)
	{
		//constexpr int PRIME_NUMBER = 198491317;
		return (float)(ONE_OVER_MAX_INT * Get2dNoiseUint(PositionX, PositionY, Seed));
	}

	/**
 * @brief This function generates a 3D noise value between -1 and 1.
 *
 * The function takes in the x, y, z coordinates of the position for which we want to generate noise, as well as a seed for the random number generator. It uses this information along with some pre-defined constants (like ONE_OVER_MAX_INT) to calculate and return a 3D noise value between -1 and 1.
 *
 * @param PositionX The x coordinate of the position for which we want to generate noise.
 * @param PositionY The y coordinate of the position for which we want to generate noise.
 * @param PositionZ The z coordinate of the position for which we want to generate noise.
 * @param Seed A seed for the random number generator used in generating the noise value.
 * 
 * @return Returns a float between -1 and 1 representing the calculated 3D noise value.
 */
/**
 * @brief This function generates a 3D noise value between -1 and 1.
 * 
 * The function takes in the x, y, z coordinates of the position to generate the noise for, as well as a seed for the random number generation. It uses the Get3dNoiseUint() function internally to get an unsigned integer noise value, which it then scales down by ONE_OVER_MAX_INT and converts to float before returning.
 * 
 * @param PositionX The x coordinate of the position to generate the noise for.
 * @param PositionY The y coordinate of the position to generate the noise for.
 * @param PositionZ The z coordinate of the position to generate the noise for.
 * @param Seed A seed for the random number generation.
 * 
 * @return A float representing a 3D noise value between -1 and 1.
 */
float SquirrelNoise::Get3dNoiseNegOneToOne(int PositionX, int PositionY, int PositionZ, uint32_t Seed)
	{
		//constexpr int PRIME_NUMBER1 = 198491317;
		//constexpr int PRIME_NUMBER2 = 6542989;
		return (float)(ONE_OVER_MAX_INT * Get3dNoiseUint(PositionX, PositionY, PositionZ, Seed));
	}

	/**
 * @brief This function generates a four-dimensional noise value between -1 and 1.
 * 
 * The function uses the Get4dNoiseUint() method to generate an integer noise value, then scales it by ONE_OVER_MAX_INT to get a float value in the range [0, 1]. This is then scaled by 2 and subtracted from 3 to get a value in the range [-1, 1].
 * 
 * @param PositionX The x-coordinate of the position for which to generate noise.
 * @param PositionY The y-coordinate of the position for which to generate noise.
 * @param PositionZ The z-coordinate of the position for which to generate noise.
 * @param PositionW The w-coordinate of the position for which to generate noise.
 * @param Seed A seed value used to initialize the random number generator.
 * 
 * @return A float value representing the four-dimensional noise at the given position and with the given seed. This will be in the range [-1, 1].
 */
/**
 * @brief This function generates a four-dimensional noise value between -1 and 1.
 * 
 * The function takes in the positions (x, y, z, w) and a seed to generate a pseudorandom number. It then scales this number by one over the maximum integer value to get a floating point number between 0 and 1. This is then multiplied by -1 and 1 to get a noise value between -1 and 1.
 * 
 * @param PositionX The x position in the noise space.
 * @param PositionY The y position in the noise space.
 * @param PositionZ The z position in the noise space.
 * @param PositionW The w position in the noise space.
 * @param Seed A seed for the pseudorandom number generator.
 * 
 * @return A floating point value between -1 and 1 representing a four-dimensional noise value.
 */
float SquirrelNoise::Get4dNoiseNegOneToOne(int PositionX, int PositionY, int PositionZ, int PositionW, uint32_t Seed)
	{
		//constexpr int PRIME_NUMBER1 = 198491317;
		//constexpr int PRIME_NUMBER2 = 6542989;
		//constexpr int PRIME_NUMBER3 = 73939;
		return (float)(ONE_OVER_MAX_INT * Get4dNoiseUint(PositionX, PositionY, PositionZ, PositionW, Seed));
	}
	

	/**
 * @brief Computes a one-dimensional noise value for a given rotation and seed.
 *
 * This function uses a combination of bitwise operations to generate a pseudorandom number based on the input parameters. The result is then clamped between 1 and ONE_OVER_MAX_UINT, which are constants defined in the SquirrelNoise class.
 *
 * @param Rotation The rotation value used as an input for the noise generation.
 * @param Seed A seed value to initialize the random number generator.
 * @return A float value representing a one-dimensional noise value.
 */

float SquirrelNoise::Get1dNoiseForRotation(int Rotation, uint32_t Seed)
	{
		constexpr unsigned int BIT_NOISE1 = 0xB5297A4D;
		constexpr unsigned int BIT_NOISE2 = 0x68E31DA4;
		constexpr unsigned int BIT_NOISE3 = 0x1B56C4E9;

		unsigned int mangled = (uint32_t)Rotation;
		mangled *= BIT_NOISE1;
		mangled += Seed;
		mangled ^= (mangled >> 8);
		mangled += BIT_NOISE2;
		mangled ^= (mangled << 8);
		mangled *= BIT_NOISE3;
		mangled ^= (mangled >> 8);

		return (float)std::clamp(mangled, 1u, ONE_OVER_MAX_UINT);
	}

}

